#!/usr/bin/env python3
"""Every truncation flag on a response contract must be documented, per owning type.

A tool that cannot return everything sets a `*Truncated` boolean rather than failing.
That is a reasonable contract for a machine client -- better than a warning string it
would have to parse -- but only if the client knows the field exists. A flag nobody
documented is a partial answer delivered silently.

Measured when this guard was written: 9 of 23 flag names across 16 response types appeared
nowhere under `docs/`, including `SelectionExportPropertiesResponse.RowsTruncated` on a
tool that writes a file, where the consequence is a report short of rows.

The first version of this guard checked only that the flag NAME appeared somewhere in
`docs/`. A review pointed out the hole: a brand-new response type reusing a common name
such as `Truncated` passes immediately, because that word is already in the prose, so the
guard would not force a word about the new type. It now compares the full
flag-and-owner inventory against a generated block in the contracts document, the same way
`check_mcp_command_catalog.py` pins the tool index -- so a new pair has to be written down,
and a removed one cannot linger.

Run with `--update` to rewrite the block from the contracts.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


BEGIN_MARKER = "<!-- BEGIN GENERATED TRUNCATION FLAG INVENTORY -->"
END_MARKER = "<!-- END GENERATED TRUNCATION FLAG INVENTORY -->"
DOC_RELATIVE_PATH = "docs/MCP_TOOL_CONTRACTS.md"


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def collect_pairs(contracts_dir: Path) -> dict[str, list[str]]:
    """Maps each truncation flag to the sorted contract types that declare it."""
    pairs: dict[str, set[str]] = {}
    class_pattern = re.compile(r"public\s+(?:sealed\s+)?class\s+(\w+)")
    flag_pattern = re.compile(r"public\s+bool\??\s+(\w*Truncated)\s*\{")

    for path in sorted(contracts_dir.rglob("*.cs")):
        current_class = "<unknown>"
        for line in path.read_text(encoding="utf-8-sig").splitlines():
            class_match = class_pattern.search(line)
            if class_match:
                current_class = class_match.group(1)
                continue
            flag_match = flag_pattern.search(line)
            if flag_match:
                pairs.setdefault(flag_match.group(1), set()).add(current_class)

    return {name: sorted(owners) for name, owners in sorted(pairs.items())}


def render_block(pairs: dict[str, list[str]]) -> str:
    lines = [
        BEGIN_MARKER,
        "",
        "Generated by `scripts/check_truncation_flags_documented.py`. Every flag below is",
        "described in the two tables above; this block exists so that adding one to a",
        "contract cannot skip that description.",
        "",
        "| flag | declared on |",
        "| --- | --- |",
    ]
    for name, owners in pairs.items():
        lines.append("| `%s` | %s |" % (name, ", ".join("`%s`" % o for o in owners)))
    lines.extend(["", END_MARKER])
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--update", action="store_true", help="rewrite the generated block")
    args = parser.parse_args(argv)

    root = repo_root()
    contracts = root / "NavisHelper.Contracts"
    doc_path = root / DOC_RELATIVE_PATH

    if not contracts.is_dir():
        print(f"{contracts} is missing; re-point this guard.")
        return 1
    if not doc_path.is_file():
        print(f"{doc_path} is missing; re-point this guard.")
        return 1

    pairs = collect_pairs(contracts)
    if not pairs:
        print("No truncation flags found in the contracts; re-point this guard.")
        return 1

    text = doc_path.read_text(encoding="utf-8-sig")
    if BEGIN_MARKER not in text or END_MARKER not in text:
        print(f"{DOC_RELATIVE_PATH} has no generated truncation-flag block.")
        print("Run: python scripts/check_truncation_flags_documented.py --update")
        return 1

    before, rest = text.split(BEGIN_MARKER, 1)
    _current, after = rest.split(END_MARKER, 1)
    expected = render_block(pairs)

    if args.update:
        doc_path.write_text(before + expected + after, encoding="utf-8", newline="\n")
        print(f"Updated the truncation-flag inventory: {len(pairs)} flags.")
        return 0

    actual = BEGIN_MARKER + _current + END_MARKER
    if actual.strip() != expected.strip():
        print("The truncation-flag inventory in " + DOC_RELATIVE_PATH + " is out of date.")
        print("A flag was added, removed, or moved to another contract without being")
        print("described. A caller cannot handle a partial answer it does not know it can")
        print("receive.")
        print()
        print("Run: python scripts/check_truncation_flags_documented.py --update")
        print("then describe the change in the tables above the block.")
        return 1

    print(f"All {len(pairs)} truncation flags are listed with their owning contracts.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
